### ISSUE TITLE
Dont save data in .rpp if not used

### ISSUE THREAD

**Issue by X-Raym** [Burtan/LivePresetsExtension#18]
Hi,

Installing this extension makes every new saved .rpp get an entry under the <EXTENSION chunk of the .rpp

```
    <LIVEPRESETS
      <LIVEPRESETSMODEL
        VERSION 1
        UNDO 0
        HIDEMUTEDTRACKS 0
        RESELECTPRESETS 0
        RESELECTFXPRESETS 0
        LOADMUTED 0
        DEFAULTFILTER ""
      >
    >
 ```

This trigger a warning popup when the .rpp is opened in a REAPER without the extension installed.

Would it make sense to store data in <EXTENSION extstate only the plugin window isn't run ?

I had to make a script to clean this chunk from all .rpp (thousands of them).

Thanks !

**Comment by Burtan** [comment]
I guess it is reasonable to only save data when there is at least one preset.

**Comment by X-Raym** [comment]
That was quick thx !
